### ISSUE TITLE
FR: water wheel and rain catcher

### ISSUE THREAD

**Issue by DropbearNinja** [Dubwise56/Dubs-Bad-Hygiene#21]
Hey Dubwise, love DBH, great mod. I wanted to add 2 things though; at present there's only 1 water source, but naturally there exists 2 water sources that are untapped.... rivers and rain. I looked at the code to see if I could write the additions myself, but it's way beyond me. Hence I am hopefully requesting this feature request:

1. a water wheel. place by river, acts as both a well and pump. It's naturally slower than a dedicated pump/well, but only 1 building and doesn't require power.

2. Rain catcher. a big funnel. doesn't require power, obviously only works during rain, but during heavy rain it produces astronomical amounts of very clean water.

**Comment by noobydp** [comment]
+1

**Comment by Dubwise56** [comment]
I didn't bother adding any water wheels because windmill + well on a river does exactly the same thing really, and i get complaints there's too many buildings so i need to stop adding stuff, especially when it does basically the same job as something else.

If you want to add a rain catcher i added some settings to the storage comp to let you generate water, it can be used like this

`<comps>
      <li Class="DubsBadHygiene.CompProperties_WaterStorage">
        <WaterStorageCap>8000</WaterStorageCap>
        <AutoOnRain>true</AutoOnRain>
        <AutoGenRate>10</AutoGenRate>
      </li>
    </comps>`

**Comment by Dubwise56** [comment]
i made it so water tubs catch rain water when unroofed in a recent update
