### ISSUE TITLE
suggestion -> more water source acess like oceans

### ISSUE THREAD

**Issue by shivachirr** [Dubwise56/Dubs-Bad-Hygiene#29]
i was thinking as of right now the only source of water for the entire mod is just ground water. and yet there are rivers, oceans, lakes, and marshes. i say for oceans you pump up salt water which is undrinkable and you need a distilling plant to separate the water and salt. and for rivers maybe some kind of pump for it while it can easily raise or lower disease risk and contamination chance. and for marshes and lakes as you pull from them they drain over time and have the highest disease risk and contamination chance due to them being pretty much stagnant and possibly algae filled water sources. im kinda surprised this has not been explored or done yet

**Comment by Dubwise56** [comment]
The ground water is generated by rivers and lakes so when you're placing a well you're accessing river and lake water anyway, the fact its called "well" and not "inlet" doesn't really make much difference when it comes to how it would be coded, the point of this was so i don't have to add water inlets + wells which would both end up accessing the same water grid anyway, else i would need to create yet another water grid for just surface water, and where shallow water meets river or lake water it would have to prioritize the river and lake water and filter it out from the shallow water grid and yada yada its much easier to make it 1 grid, people already complain that pipes and wells are too complicated to understand hence all these requests for lite versions with none of it.

I'm not really interested in adding desalination, bit of a waste when you can just use the normal water grids since they generate on every map by default, also overcomplicates the mod even more.
