### ISSUE TITLE
Feature Request: Swimming and bathing in natural water sources

### ISSUE THREAD

**Issue by TinyGecko** [Dubwise56/Dubs-Bad-Hygiene#9]
Now that there are swimming pools it would be awesome when bathing and swimming could be extended to oceans, rivers and lakes when the outside temperature is warm enough.
Maybe by designating a swimming area on valid terrain?

**Comment by Dubwise56** [comment]
cant do that, it works by rendering multiple layers on the pool, swimming in surface water they would just be a decapitated head floating around and it looks really weird, i tried it

**Comment by TinyGecko** [comment]
What if bathing or wading in natural water sources would be limited to shallow water so that there's no need to render the body invisible? When they walk through it you can see their bodies too. Shallow water on the Rimworld seems to be too shallow for swimming, which explains the low movement penality.

It also means you don't have to mess around with issues that may arise from making deep water areas passable.

Please don't have this feature off the table yet! It could be an experimental feature that is off by default.

**Comment by Dubwise56** [comment]
uuuuuuum, i guess so but the problem is people always want a bit more so then its like well do bodyless in deep water not in shallow and, i would have to do extra job drivers and workers for all of it since the pool one is very specific to pools, would need to have debuffs since it could be a dirty river, then also stuff like ways to prevent pawns swimming in random rivers outside your base that you dont want them to so you start getting into like designating a swimming area with a custom area system, thats usually what happens with a small ideas like this, and it took long enough just to get the pool to work as a small bonus feature on its own, right now i need to prioritise a lot of other stuff in my other mods

**Comment by TinyGecko** [comment]
When they ask for bodyless in deep water you just tell them "swimming in surface water they would just be a decapitated head floating around and it looks really weird, i tried it". :D
But of course I understand when you currently don't have time for this.
Still thanks for your attention and the replies!

**Comment by TinyGecko** [comment]
I like how this issue is still open, indicating that somewhere along the way when the planets align it still could happen. :)
